# Compose file for the CueCode dev environment.
name: cuecode-dev
services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    restart: unless-stopped
    ports:
      - 2345:80
    env_file: .env
    volumes:
      - pgadmindata:/var/lib/pgadmin

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "1337:8081"
#  dbmate:
#    image: ghcr.io/amacneil/dbmate:main
#    env_file: .env
#    volumes:
#      - ./db:/db
#    depends_on:
#      - postgres
#    entrypoint: [ "sh", "/db/dbmate-entrypoint.sh" ]

volumes:
  pgdata:
  pgadmindata:
  redisdata:
