# Compose file for the CueCode dev environment.
name: cuecode-dev
services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    restart: unless-stopped
    ports:
      - 127.0.0.1:2345:80
    env_file: .env
    volumes:
      - pgadmindata:/var/lib/pgadmin

  dbmate:
    image: ghcr.io/amacneil/dbmate:main
    env_file: .env
    volumes:
      - ./db:/db
    depends_on:
      - postgres
    entrypoint: [ "sh", "/db/dbmate-entrypoint.sh" ]

volumes:
  pgdata:
  pgadmindata:
