# This config used from the following source, which also documents the pylint
# extension in use:
# https://github.com/DetachHead/pylint-module-boundaries/blob/master/README.md
[tool.pylint.MASTER]
load-plugins = "pylint_module_boundaries"
banned-imports = '''
{
    "common(\\..*)?": ["app(\\..*)?", "configuration(\\..*)?", "runtime(\\..*)?"],
    "app(\\..*)?": ["configuration(\\..*)?", "runtime(\\..*)?"],
    "configuration(\\..*)?": ["app(\\..*)?", "runtime(\\..*)?"],
    "runtime(\\..*)?": ["configuration(\\..*)?", "app(\\..*)?"]
}
'''
banned-imports-check-usages = true
