# Adapted from the Python template repository at the following link on Jan 18, 2025
# https://github.com/ConsciousML/python-template/blob/main/.github/workflows/main-ci.yml

name: main-ci
run-name: Running Main CI by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint bandit mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f setup.py ]; then pip install setuptools && python setup.py install --force; fi

      - name: Run Pytest to run unit tests
        run: pytest

      - name: Run Pylint to check code quality
        run: pylint $(git ls-files '*.py')

      - name: Run Black to check code style
        run: black $(git ls-files "*.py") --check --verbose

      - name: Run Mypy to check static types
        run: mypy $(git ls-files '*.py')
