# Adapted from the Python template repository at the following link on Jan 18, 2025
# https://github.com/ConsciousML/python-template/blob/main/.github/workflows/main-ci.yml
# Be sure to update the Makefile if you update what is run here, in particular
# the "all-checks" target, which is meant to perform the same checks locally
# as this runner does as part of GitHub Actions.

name: main-ci
run-name: Running Main CI by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"

jobs:
  run-checks:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:

      - name: Install Dbmate
        run: sudo curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64 && sudo chmod +x /usr/local/bin/dbmate
  
      - uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip

      - name: Install dependencies and run checks
        run: make -j2 all-checks

